version: "3.8"

services:
  go-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    networks:
      - app-network

  node-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
